---
- hosts: localhost
  gather_facts: False
  connection: local
  roles:
    - { role: apstra_auth }
    - { role: get_bp_id }


  tasks:
    - name: read port template from csv file
      community.general.read_csv:
        path: "{{ portsfile }}"
        delimiter: ";"
      register: ports
     

    - name: show ports
      ansible.builtin.debug:
        msg: "{{ ports }}"
    
    - name: include create_switch_portdescription
      ansible.builtin.include_role:
        name: create_switch_portdescription
      loop: "{{ ports.list }}"
      loop_control:
        loop_var: gensystem
    
