---
- hosts: localhost
  gather_facts: False
  connection: local
  roles:
    - { role: apstra_auth }
    - { role: get_bp_id }


  tasks:
    - name: read port template from csv file
      community.general.read_csv:
        path: "{{ portsfile }}"
        delimiter: ";"
      register: ports
     

    - name: read vni template from csv file
      community.general.read_csv:
        path: "{{ vnisfile }}"
        delimiter: ";"
      register: vnis



    - name: show ports
      ansible.builtin.debug:
        msg: "{{ ports }}"
    
    - name: show vnis
      ansible.builtin.debug:
        msg: "{{ vnis.list }}"


    
    - name: set sz and vni data structure
      ansible.builtin.set_fact:
        vnimap: "{{ lookup('ansible.builtin.template', './templates/convert-excel-ds-flat.j2') | to_json | from_json }}"


    
    
    - name: include create_vn role
      ansible.builtin.include_role:        
        name: create_vn_from_flat_list
      loop: "{{ vnimap }}"
      loop_control:
        loop_var: vn

    - name: include create_connectivity template role
      ansible.builtin.include_role:        
        name: create_ct_from_flat_list
      loop: "{{ vnimap }}"
      loop_control:
        loop_var: vn

    - name: consolidate ports of the same host in single dictionary
      ansible.builtin.set_fact:
        portlist: "{{ ports.list | consolidate_port_raws_in_csv }}"

    - name: include create_switch_system role
      ansible.builtin.include_role:
        name: create_switch_system
      loop: "{{ portlist }}"
      loop_control:
        loop_var: gensystem
        
