---
- hosts: localhost
  gather_facts: False
  connection: local

  tasks:
    - name: read port template from csv file
      community.general.read_csv:
        path: "{{ portsfile }}"
        delimiter: ";"
      register: ports
     

    - name: read vni template from csv file
      community.general.read_csv:
        path: "{{ vnisfile }}"
        delimiter: ";"
      register: vnis



    - name: show ports
      ansible.builtin.debug:
        msg: "{{ ports }}"
    
    - name: show vnis
      ansible.builtin.debug:
        msg: "{{ vnis.list }}"


    - name: create sz raw list variable
      ansible.builtin.set_fact:
        sz_list_raw: []


    - name: fill sz  raw list
      ansible.builtin.set_fact:
        sz_list_raw: "{{ sz_list_raw + [ item.VRF ] }}"
      loop: "{{ vnis.list }}"

    - name: set raw list
      ansible.builtin.set_fact:
        sz_list: "{{ sz_list_raw | unique }}"

    

    - name: set sz and vni data structure
      ansible.builtin.set_fact:
        vnimap: "{{ lookup('ansible.builtin.template', './templates/convert-excel-ds.j2') | to_json | from_json }}"

    - name: set sz and vni data structure2
      ansible.builtin.set_fact:
        vnimap2: "{{ lookup('ansible.builtin.template', './templates/convert-excel-ds-flat.j2') | to_json | from_json }}"

    - name: show vnimap2
      ansible.builtin.debug:
        msg: "{{ vnimap2 }}"


    - name: consolidate ports of the same host in single dictionary
      ansible.builtin.set_fact:
        portlist: "{{ ports.list | consolidate_port_raws_in_csv }}"

    - name: show portlist
      ansible.builtin.debug:
        msg: "{{ portlist }}"

