---
#apstra:
#  username: "admin"
#  password: "S3kom123!"
#  baseurl: "https://10.106.20.29/api"
#bp_name: "ISA-BP"          ### Blueprint name

  
bp_name: "_TT_Umitkoy"          ### Blueprint name
apstra:
  username: "ansible-admin"
  password: "Dc0@Apstra2024"
  baseurl: "https://10.98.170.34/api"

