---
# tasks file for assosicate_ct_request



- name: narrow down the ct_name list
  ansible.builtin.set_fact:
    ct_name_list: "{{ ct_qry.json | dict2items }}"


- name: create ct_name list id variable
  ansible.builtin.set_fact:
    ct_name_list_id: []


- name: ct_name list with id
  ansible.builtin.set_fact:
     ct_name_list_id: "{{ ct_name_list_id + [ item[ct_name].id ] }}"
  ignore_errors: yes
  when:
    - item['ct'].id != None and item['ct'].label == ct_name
  loop: "{{ ct_name_list[0].value }}"



- name: show request body
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.template', './templates/assign-connectivity-template.j2') }}"
  loop: "{{ interface_ids }}"



- name: Associate connectivity template with interface
  ansible.builtin.uri:
    url: "{{ apstra.baseurl }}/blueprints/{{ bp_id }}/obj-policy-batch-apply?async=full"
    method: PATCH
    status_code: 202
    headers:
      content-type: "application/json"
      AUTHTOKEN: "{{ login.json.token }}"
    validate_certs: false
    force_basic_auth: yes
    body: "{{ lookup('ansible.builtin.template', './templates/assign-connectivity-template.j2') }}"
    body_format: json
  ignore_errors: true
  loop: "{{ interface_ids }}"





